site_name: FishFeats Documentation
site_url: https://gletort.github.io/FishFeats/
repo_url: https://github.com/gletort/FishFeats/

nav:
    - Home: index.md
    - Steps:
        - Image Scalings: Image-scalings.md
        - Get Cells: Get-cells.md

theme:
    name: material
    features:
        - navigation.footer
    color_mode: dark
    palette:
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: white
          accent: teal
          toggle:
            icon: material/lightbulb
            name: Switch to light mode
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: white
          accent: dark blue
          toggle:
            icon: material/lightbulb-outline
            name: Switch to dark mode

    icon:
        annotation: material/plus-circle-outline
        admonition:
            note: fontawesome/solid/note-sticky
            abstract: fontawesome/solid/puzzle-piece
            bug: fontawesome/solid/bug
            tip: fontawesome/solid/keyboard
            warning: fontawesome/solid/triangle-exclamation


## display code options
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

